[project]
name = "ppcg"
version = "0.1.0"
description = "An implementation of the PPCG algorithm for the standard eigenvalue problem."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "scipy>=1.16.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
